<?xml version="1.0" encoding="utf-8"?><Database Name="Wineoutlet" Class="WineOutletDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SAVVY-LOKESH\SQLEXPRESS;Initial Catalog=Wineoutlet;Integrated Security=True" SettingsObjectName="Wineoutlet.DataAccess.Properties.Settings" SettingsPropertyName="WineoutletConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetItemDetails" Method="GetItemDetails">
    <Parameter Name="Sku" Parameter="sku" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetItemDetailsResult">
      <Column Name="Sku" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Vintage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="RegionName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="SubRegionName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="GrapeTypeName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="WineTypeName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetItemsByCountryId" Method="GetItemsByCountryId">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetItemsByCountryIdResult">
      <Column Name="Sku" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Vintage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="RegionName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="SubRegionName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="GrapeTypeName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="WineTypeName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetItemsByGrapeTypeId" Method="GetItemsByGrapeTypeId">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetItemsByGrapeTypeIdResult">
      <Column Name="Sku" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Vintage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="RegionName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="SubRegionName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="GrapeTypeName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="WineTypeName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetItemsByRegionId" Method="GetItemsByRegionId">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetItemsByRegionIdResult">
      <Column Name="Sku" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Vintage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="RegionName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="SubRegionName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="GrapeTypeName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="WineTypeName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetItemsBySubRegionId" Method="GetItemsBySubRegionId">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetItemsBySubRegionIdResult">
      <Column Name="Sku" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Vintage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="RegionName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="SubRegionName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="GrapeTypeName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="WineTypeName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetItemsByWineTypeId" Method="GetItemsByWineTypeId">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetItemsByWineTypeIdResult">
      <Column Name="Sku" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Vintage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="RegionName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="SubRegionName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="GrapeTypeName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="WineTypeName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetItemNames" Method="GetItemNames">
    <ElementType Name="GetItemNamesResult">
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>